#define COMBO_ALLOW_ACTION_KEYS 
#define COMBO_VARIABLE_LEN
#define TAPPING_FORCE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#undef CONSOLE_ENABLE
#define NKRO_ENABLE
#define COMBO_PERMISSIVE_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 170
#define TAPPING_TERM_PER_KEY
