OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
ENCODER_ENABLE = no       # Enables the use of one or more
WPM_ENABLE = yes
CONSOLE_ENABLE = no     # Console for debug
AUDIO_ENABLE   = no     # Audio output
SPACE_CADET_ENABLE = no
EXTRAKEY_ENABLE = no
MOUSEKEY_ENABLE = no
BOOTMAGIC_ENABLE = no
SWAP_HANDS_ENABLE = no
LTO_ENABLE = yes
